### ISSUE TITLE
About using the pre-trained model

### ISSUE THREAD

**Issue by RJ-Lupin** [Patchouli-M/SequencingCancerFinder#1]
Thank you for developing such a wonderful method. 
I have a question regarding its applicability to my own dataset. In your publication, you tested the method on BRCA, CRC, HCC, and RCC datasets to detect malignant areas in the 10x Visium dataset. However, my dataset pertains to lung cancer (10x Visium dataset).

Therefore, I'm curious: is it feasible to utilize the pre-trained model available on your GitHub repository for my specific case of lung cancer, or would it be advisable to build a new model from scratch?

Thank you, and congratulations on your publication.

**Comment by Patchouli-M** [comment]
Thank you for your attention.

In theory, it is feasible, and existing models demonstrate some level of generalization. However, we haven't tested it on 10x Visium lung cancer data yet, so I'm unsure about its specific performance. Therefore, I recommend treating the predictions of the existing model as a reference only.

I would also suggest using reliable manual annotations as a standard for validation or considering retraining to ensure the accuracy on your data.

Thank you for your attention and feedback.

**Comment by Patchouli-M** [comment]
Thank you for your interest.

In theory, it is feasible, and existing models demonstrate some level of generalization. However, we haven't tested it on 10x Visium lung cancer data yet, so I'm unsure about its specific performance. Therefore, I recommend treating the predictions of the existing model as a reference only.

I would also suggest using reliable manual annotations as a standard for validation or considering retraining to ensure the accuracy on your data.

Thank you for your attention and feedback.
