### ISSUE TITLE
Question about running it on mouse spatial transcriptomics?

### ISSUE THREAD

**Issue by Zjianglin** [Patchouli-M/SequencingCancerFinder#10]
Hi, I have several BGI `stereo-seq` ST data of mouse liver cancer data. I'd like to known whether `CancerFinder` can be applied to it to find cancer cells and how to do it? And if it can be run, what the threshold should be set for `stereo-seq` data. Thanks.

**Comment by Patchouli-M** [comment]
Hi, the current pre-trained models have only been trained using human cancer data, and I have not tried to infer on mouse data.
Similarly, I have not tried to infer on stereo-seq data.
In theory, it is recommended to train with more mouse data that is similar in resolution to stereo-seq before using it.

However, I am also very interested in the effects of applying human pre-trained models to mouse data. If you have conducted any relevant experiments, I look forward to further communication on this topic.
