### ISSUE TITLE
Detailed sources of MERFISH data in Figure 5d and supplementary Figure 7a

### ISSUE THREAD

**Issue by MNXIAOJIA123** [Patchouli-M/SequencingCancerFinder#13]
Cancer-Finder is an amazing tool, and your analysis in the paper is excellent. Could you please provide detailed sources of MERFISH data in Figure 5d and Supplementary Figure 7a, such as which sample and which fov these analyses come from? Looking forward to your kind answer.

**Comment by Patchouli-M** [comment]
Figure 5d is about 10x Visium. Did you mean Figure 4d? The MERFISH data used are from the MERSCOPE website, with the link provided in the 'Data Availability' section of the article. You can find the corresponding datasets for different cancer types on the website, where each image displayed in the paper corresponds to a dataset from the MERSCOPE website. There should be only about 10~20 datasets in total. You can try plotting them, and you'll be able to find the one you're looking for.
