### ISSUE TITLE
Quality Control for scRNAseq data

### ISSUE THREAD

**Issue by jslee6381** [Patchouli-M/SequencingCancerFinder#5]
Hey there, I wanted to express my appreciation for the excellent work you've done!

I'm curious, did you conduct quality control (QC) before training and evaluating the model? If so, Could you please let me know your QC metrics, such as nGene, nUMI, and the percentage of mitochondria?

Thank you!

**Comment by Patchouli-M** [comment]
Thank you for your attention. 
The data I used were directly downloaded from datasets or databases as expression matrices, with the upstream QC already performed by others. I did not conduct any additional QC.
