### ISSUE TITLE
Customize pre-trained model

### ISSUE THREAD

**Issue by jslee6381** [Patchouli-M/SequencingCancerFinder#6]
Hi,

Thank you for your excellent work!

I am attempting to classify brain cells in my samples, which include GBM and Glioma cells. The performance has been good, but I would like to train the model on my dataset to customize the pre-trained model. Could you kindly guide(ex. input formats for training/validation data) running your training Python code (train.py and train_gene_set.py)?

Thank you!

**Comment by Patchouli-M** [comment]
Thank you for your attention.
Information on how to train can be found in the "Usage and Options - Train" section of the README.md file. The organization of the data can refer to the "data" folder in the project. It is recommended to use expression matrices in ".tsv" or ".csv" file formats for training and validation data.
Good luck!
