### ISSUE TITLE
figures reproducibility for Figs. 4, 5 and Supp Fig. 5

### ISSUE THREAD

**Issue by mtoseef99** [Patchouli-M/SequencingCancerFinder#9]
Thank you for this great tool!

Could you please provide instructions on reproducing figures for ST data, such as Figs. 4, 5 and Supp Fig. 5?

Further, I am trying to test Cancer-Finder for my own data ([pancreatic cancer data from 10x](https://www.10xgenomics.com/datasets/pancreatic-cancer-with-xenium-human-multi-tissue-and-cancer-panel-1-standard)). Do we only need to replace the gene expression matrix (while testing for ST data) with sample data as domain 2? Looking forward to your response. Thanks so much!

**Comment by Patchouli-M** [comment]
Thank you for your interest.
If it's for reproduction and testing purposes, there is no need for training or "Domain" data.
You can download the pre-trained ST model provided in the "readme.md", replace the expression matrix in the "Sample_data" file, and then execute the infer.py script to proceed.
